### ISSUE TITLE
Just wondering if you used a NoSQL graph Database for this

### ISSUE THREAD

**Issue by busman84** [ibaaj/dijkstra-cartography#2]
Hello, I was wondering if you used some sort of no sql graph db for this... This project is awesome btw

**Comment by ibaaj** [comment]
I started with PostgreSQL but finally not.
You need to have very fast access to data, and ram is far more effective. 
Then I store the data (json file, or C++ serialized map<> with boost) before drawing the map. I made sometimes backups in case of if my program crashed (and kept a point to know "where/when" the program stopped).
Railway data is about 350MB (the biggest file).

**Comment by karussell** [comment]
You could use the map data of the routing engine itself which should be also a lot faster and outlined in #3

**Comment by busman84** [comment]
Awesome... thanks for the info.  This is really cool stuff
