### ISSUE TITLE
Kind of open source

### ISSUE THREAD

**Issue by karussell** [ibaaj/dijkstra-cartography#3]
The roads to rome is indeed not open source although (as you already stated) the tools are and I was playing around with this and GraphHopper as well [here](https://graphhopper.com/blog/2016/01/19/alternative-roads-to-rome/)

Using some simple modification of the MiniUIGraph tool which you can find [here](https://gist.github.com/karussell/768e828a01f71ac7f46c)

The advantage is that you directly use the map data of GraphHopper without any additional DB.

**Comment by ibaaj** [comment]
Very interesting, thanks you !
I will try your gist.

**Comment by karussell** [comment]
BTW: the current planet file is just 31GB if you use the (preferred) PBF format which can be read by GraphHopper too

**Comment by ibaaj** [comment]
My main problem with GraphHopper was that it crashed a lot ... (even with a very powerful server (tested on amazon EC2 C4, or a VPS with 24cpu + 130Gb RAM))

**Comment by karussell** [comment]
Interesting. For us, our customers and our users GraphHopper is very solid and does normally need fewer RAM (in its default settings) compared to other open source routing engines. E.g. also Moovel did not report such issues although they had kind of an extreme, different approach :)

Do you have a stacktrace or something? And are you using the default settings? (And feel free to open an issue for this on graphopper itself)

**Comment by ibaaj** [comment]
I finally finished the map of Paris with my computer - Macbook Pro (mid-2012, i7, 8GB RAM) - without the help of server, I made mistake at the beginning : I thought that I needed to use a database.

my file is Paris.osm (233MB). 
My parameters was : 15 threads max, RAM_STORE.

I can't find any interesting log, I executed "cat logGrapphopper | grep Exception" and only get results when Graphhopper response with a JSON string that the "error" is that there is no link between the two points (so, it's not a "Java error").

**Comment by karussell** [comment]
Using RAM_STORE is the default&good and recommended

> My parameters was : 15 threads max

where did you specify these threads? For `prepare.threads=1`? Here you should just keep 1, using 2 roughly doubles RAM requirements and should be only increased if you succeeded with 1. And using more makes it even worse (but only if you use multiple vehicles or we say 'flagEncoders')

> I can't find any interesting log, I executed "cat logGrapphopper | grep Exception" 

But how did it crashed and what was the message for that then? Per default the logs go just into stdout but you can easily pipe them.

**Comment by ibaaj** [comment]
Yes `prepare.threads`. Okay I notice my error, but I thought that my computer was enough robust because Graphhopper crashed after a lot of requests where queried (we talk of 10^5+)

I executed Grapphopper each time like this : 

```
 java -jar *.jar jetty.resourcebase=webapp config=config-example.properties \ 
osmreader.osm=PARIS.osm >logGraphhopper 2>&1 &
```

So I have log files.

**Comment by karussell** [comment]
Ok, nice that you have logs. Is there anything meaningful at the end of the log where GH crashed?

Again, GH should be very robust (and if not we need to fix this!) as indeed 10⁵ is not much :)

**Comment by karussell** [comment]
Forgot this question: On EC2 which particular instance did you choose? And only the city Paris or whole France? Although even France should be possible on the smallest instance c4.large with 'only' 3.75gb RAM

**Comment by ibaaj** [comment]
I tried many grep within my logs file but I can't find anything relevant [...]. I will dig tomorrow too. 
Note that in my app I never used a sleep function within the loop. The thing that I noticed was that when I increased the "threads number" it worked faster [...].
My Paris.osm file is about 233MB, so I chose the less expensive amazon EC2 C4.
The situation was like this :  in the first time I executed a SQL query (I thought that I needed a database for this) into the loop.

The query was very hard to handle for the database, I found a snippet of its development : 

``` javascript
var req = 'WITH new_values (x0, y0, x1, y1, hits) as ('
            + '  values'
            + '     ($1::float, $2::float, $3::float, $4::float, 1)'
            + '),'
            + 'upsert as '
            + '('
            + '    update edges m '
            + '        set hits = m.hits+1 '
            + '    FROM new_values nv '
            + '    WHERE '
            + '       m.x0 = nv.x0 '
            + '      AND '
            + '       m.y0 = nv.y0 '
            + '      AND '
            + '       m.x1 = nv.x1 '
            + '      AND '
            + '       m.y1 = nv.y1 '
            + '    RETURNING m.* '
            + ')'
            + 'INSERT INTO edges (x0, y0, x1, y1, hits) '
            + 'SELECT x0,y0,x1,y1,hits '
            + 'FROM new_values '
            + 'WHERE NOT EXISTS (SELECT 1 '
            + '                  FROM upsert up '
            + '                  WHERE '
            + '                  up.x0 = new_values.x0 '
            + '                    AND '
            + '                  up.y0 = new_values.y0 '
            + '                    AND '
            + '                  up.x1 = new_values.x1 '
            + '                    AND '
            + '                  up.y1 = new_values.y1 '
            + ');';
```

 (I updated this script later, it's a "update or insert" query).
PostgreSQL got a very hard time with this and it may cause Graphhopper crashs. 
For fun I used the most expensive amazon EC2 C4 instance available (not a long time..), and I understood that the problem was my program, not the computer.
I stopped to use postgresql, and started to store the data in RAM ( and do frequent backups) and used my computer. Graphhopper suffered less, but I remembered that I got crashs at the end of the loop (I was impatient and I was watching my program attentively). My nodejs script was launched with [foreverJS](https://github.com/foreverjs/forever).

**Comment by karussell** [comment]
Thanks for the investigation! Would like to know more if you have the time or if you stumble over something suspicious :)

Indeed a concurrent process could kill GraphHopper via the "OS-killer" if the RAM is "overassigned" or if the RAM gets tight the Java garbage collector kicks in using lots of CPU and even more if it cannot free enough RAM. In this case I guess the first situation is more likely and you will see something with `<application> got killed` will be in the logs or if you didn't increase the Java heap via `-Xmx` then the second situation can happen.
